# Generated by Django 6.1.1 on 2026-10-03 08:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('filename', models.CharField(max_length=255)),
                ('bank_selected', models.CharField(max_length=50)),
                ('include_summary', models.BooleanField(default=False)),
                ('export_format', models.CharField(max_length=10)),
                ('is_successful', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
